<a href="https://colab.research.google.com/github/Mal-Lem/python/blob/main/Numpy_atelier_1_starbucks_%C3%A9l%C3%A8ve.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1> Contexte </h1>

1) Contexte :
Starbucks est une chaîne de cafés américaine fondée à Seattle. Elle propose à la fois des boissons et de la nourriture.

2) Contenu :
Ce jeu de données contient les informations nutritionnelles des produits alimentaires et des boissons proposés par Starbucks. Toutes les informations nutritionnelles pour les boissons correspondent à une portion de 12 oz (soit environ une canette de soda de 33 centilitres)


<h1> Les étapes à suivre </h1>

<b> Import des données </b>
- utilisez genfromtxt pour importer les données du fichier starbucks-menu-nutrition-drinks.csv. Veillez bien à définir un type de données ainsi qu'un encodage pour importer correctement les données textuelles

aide : si vous obteniez un préfixe 'b' sur chaque valeur, pour pouvez tester le type 'None' pour résoudre le problème.

<b> Data Cleaning</b>
- Les données manquantes ont été symbolisées par des "-". Remplacez ces valeurs par des valeurs nulles (nan)
- Nous allons séparer les différents types de données. "header" contiendra les entête de colonne, "drinks" le nom des boissons et "data" les données numériques (veillez à bien définir le type de ce dernier)
- Certaines boisson n'ont aucune donnée numériques. A l'aide de la méthode np.isnan(...).all(...), calculez la part des boissons sans donnée.
- Filtrez les array  "drinks" et "data" pour ne garder que les boissons ayant des données

<b> Analyse des données </b>

- Calculez la moyenne des calories par boisson
- Calculez la médiane des protéines
- Calculez le maximum et le minimum des lipides (fat)
- idenfiez la boisson avec le maximum de calories (nom de la boisson + nombre de calories)
- Identifiez la boisson avec le minimum de calories (nom de la boisson + nombre de calories)

<b> Data modeling </b>

Afin de simplifier la lecture et l'analyse des boissons, nous souhaitons créer un "NutriScore" permettant d'indiquer rapidement le niveau de calorie d'une boisson :
- de 0 à 100 calories, la boisson aura le niveau 1
- de 100 à 200 calories, niveau 2
- de 200 à 300 calories, niveau 3
- 300 et plus, niveau 4

Intructions :
- Isolez la colonne des calories dans la variable "calories"
- A l'aide de la méthode "np.zeros" créez un tableau ayant la même forme que "calories" dans la variable "niveaux_calories"
- Effectuez une série de filtres pour remplacer les valeurs de "niveaux_calories" avec les valeur 1,2,3 ou 4, en fonction du niveau de calories des boissons
- Une fois cela effectué, utilisez le tableau "niveaux_calories" pour filtrer sur les boissons les moins caloriques (nutriscore 1).
- Calculez la moyenne de calories pour les boissons ayant le nutriscore 1

<h1> Import des données </h1>

In [93]:
import numpy as np
#import pandas as pd

url = ('/content/starbucks-menu-nutrition-drinks.csv')

#data = pd.read_csv(url)
#data.head()
Jdata = np.genfromtxt(url, delimiter = ',', dtype = None, encoding = 'utf-8')
Jdata


array([['Drink', 'Calories', 'Fat (g)', ..., 'Fiber (g)', 'Protein',
        'Sodium'],
       ['Cool Lime Starbucks Refreshers Beverage', '45', '0', ..., '0',
        '0', '10'],
       ['Ombré Pink Drink', '-', '-', ..., '-', '-', '-'],
       ...,
       ['Ginger Ale', '-', '-', ..., '-', '-', '-'],
       ['Lemon Ale', '-', '-', ..., '-', '-', '-'],
       ['Orange Cream Soda', '-', '-', ..., '-', '-', '-']], dtype='<U62')

<h1> Cleaning des données </h1>



**Remplacez les valeurs manquantes par des valeurs nulles (nan)**

In [94]:

Jdata[Jdata == '-'] = np.nan
Jdata

array([['Drink', 'Calories', 'Fat (g)', ..., 'Fiber (g)', 'Protein',
        'Sodium'],
       ['Cool Lime Starbucks Refreshers Beverage', '45', '0', ..., '0',
        '0', '10'],
       ['Ombré Pink Drink', 'nan', 'nan', ..., 'nan', 'nan', 'nan'],
       ...,
       ['Ginger Ale', 'nan', 'nan', ..., 'nan', 'nan', 'nan'],
       ['Lemon Ale', 'nan', 'nan', ..., 'nan', 'nan', 'nan'],
       ['Orange Cream Soda', 'nan', 'nan', ..., 'nan', 'nan', 'nan']],
      dtype='<U62')

<b> Séparation des valeurs textuelles et des valeurs numériques

In [95]:
header = Jdata[0]
drinks = Jdata[1:,0]
drinks
calorie_index = np.where(header == 'Calories')[0][0]
calorie_index

1

In [96]:
data = np.array([list(row)[1:] for row in Jdata[1:]],dtype=float)
data

array([[45.,  0., 11.,  0.,  0., 10.],
       [nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan],
       ...,
       [nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan]])

<b> Calcul la part des boisons sans données

In [97]:
mask = ~np.isnan(data).all(axis=1)
mask

array([ True, False, False,  True,  True, False, False, False,  True,
        True, False,  True,  True,  True, False, False, False, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False,  True,  True, False, False, False, False, False, False,
       False, False, False, False, False,  True,  True, False,  True,
        True,  True, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False,  True, False,  True, False,  True,
        True,  True, False,  True,  True,  True,  True,  True, False,
        True,  True,  True, False,  True,  True,  True,  True, False,
        True,  True, False, False, False,  True, False,  True,  True,
        True, False,

In [98]:
filt_drinks = drinks[mask]
filt_drinks

array(['Cool Lime Starbucks Refreshers Beverage',
       'Strawberry Acai Starbucks Refreshers Beverage',
       'Very Berry Hibiscus Starbucks Refreshers Beverage',
       'Evolution Fresh Organic Ginger Limeade', 'Iced Coffee',
       'Iced Espresso Classics - Vanilla Latte',
       'Iced Espresso Classics - Caffe Mocha',
       'Iced Espresso Classics - Caramel Macchiato', 'Shaken Sweet Tea',
       'Tazo Bottled Berry Blossom White', 'Tazo Bottled Black Mango',
       'Tazo Bottled Black with Lemon', 'Tazo Bottled Brambleberry',
       'Tazo Bottled Giant Peach', 'Tazo Bottled Iced Passion',
       'Tazo Bottled Lemon Ginger', 'Tazo Bottled Organic Black Lemonade',
       'Tazo Bottled Organic Iced Black Tea',
       'Tazo Bottled Organic Iced Green Tea',
       'Tazo Bottled Plum Pomegranate', 'Tazo Bottled Tazoberry',
       'Tazo Bottled White Cranberry', 'Teavana Shaken Iced Black Tea',
       'Teavana Shaken Iced Black Tea Lemonade',
       'Teavana Shaken Iced Green Tea',
   

In [99]:
filt_data = data[mask]
filt_data

array([[ 45. ,   0. ,  11. ,   0. ,   0. ,  10. ],
       [ 80. ,   0. ,  18. ,   1. ,   0. ,  10. ],
       [ 60. ,   0. ,  14. ,   1. ,   0. ,  10. ],
       [110. ,   0. ,  28. ,   0. ,   0. ,   5. ],
       [  0. ,   0. ,   0. ,   0. ,   0. ,   0. ],
       [130. ,   2.5,  21. ,   0. ,   5. ,  65. ],
       [140. ,   2.5,  23. ,   0. ,   5. ,  90. ],
       [130. ,   2.5,  21. ,   0. ,   5. ,  65. ],
       [ 80. ,   0. ,  19. ,   0. ,   0. ,  10. ],
       [ 60. ,   0. ,  15. ,   0. ,   0. ,  10. ],
       [150. ,   0. ,  38. ,   0. ,   0. ,  15. ],
       [140. ,   0. ,  35. ,   0. ,   0. ,  10. ],
       [140. ,   0. ,  35. ,   0. ,   0. ,  15. ],
       [150. ,   0. ,  37. ,   0. ,   0. ,  15. ],
       [ 70. ,   0. ,  17. ,   0. ,   0. ,  10. ],
       [120. ,   0. ,  31. ,   0. ,   0. ,  10. ],
       [140. ,   0. ,  35. ,   0. ,   0. ,  10. ],
       [ 60. ,   0. ,  15. ,   0. ,   0. ,  10. ],
       [120. ,   0. ,  31. ,   0. ,   0. ,  10. ],
       [140. ,   0. ,  35. ,   

In [100]:
print(f"pourcentage de boissons sans donnees : {100 - mask.mean() * 100:.2f}%")
print(f"nombre de boissons apres filtrage : {len(filt_drinks)}")

pourcentage de boissons sans donnees : 48.02%
nombre de boissons apres filtrage : 92


<h1> Analyse des données </h1>

    1.Calculez la moyenne des calories par boisson
    2.Calculez la médiane des protéines
    3.Calculez le maximum et le minimum des lipides (fat)
    4.idenfiez la boisson avec le maximum de calories (nom de la boisson + nombre de calories)
    5.Identifiez la boisson avec le minimum de calories (nom de la boisson + nombre de calories)


In [101]:
#print(header)
moyenne_calories = filt_data[:,1].mean()
print(f'la moyenne des calories par boisson est {moyenne_calories} ')

la moyenne des calories par boisson est 2.3369565217391304 


In [102]:
mediane_proteines = np.median(filt_data[:,5])
print(f'la mediane des proteines est {mediane_proteines} ')

la mediane des proteines est 15.0 


In [103]:
maximum_lipides = np.max(filt_data[:,2])
print(f'le maximum des lipides est {maximum_lipides} ')

minimum_lipides = np.min(filt_data[:,2])
print(f'le minimum des lipides est {minimum_lipides} ')

le maximum des lipides est 64.0 
le minimum des lipides est 0.0 


In [104]:
drink_max_calories = filt_drinks[filt_data[:,1].argmax()]
max_calories = filt_data[:,1].max()
print(f'la boisson avec le maximum de calories est : {drink_max_calories} avec {max_calories}')

la boisson avec le maximum de calories est : Starbucks Signature Hot Chocolate avec 26.0


In [105]:
drink_min_calories = filt_drinks[filt_data[:,1].argmin()]
min_calories = filt_data[:,1].min()
print(f'la boisson avec le minimum de calories est : {drink_min_calories} avec {min_calories}')

la boisson avec le minimum de calories est : Cool Lime Starbucks Refreshers Beverage avec 0.0


<h1> Data Modelisation </h1>

    1.Isolez la colonne des calories dans la variable "calories"
    2.A l'aide de la méthode "np.zeros" créez un tableau ayant la même forme que "calories" dans la variable "niveaux_calories"
    3.Effectuez une série de filtres pour remplacer les valeurs de "niveaux_calories" avec les valeur 1,2,3 ou 4, en fonction du niveau de calories des boissons
    4.Une fois cela effectué, utilisez le tableau "niveaux_calories" pour filtrer sur les boissons les moins caloriques (nutriscore 1).
    5.Calculez la moyenne de calories pour les boissons ayant le nutriscore 1


In [106]:
calories = filt_data[:,0]
#calories.shape
calories

array([ 45.,  80.,  60., 110.,   0., 130., 140., 130.,  80.,  60., 150.,
       140., 140., 150.,  70., 120., 140.,  60., 120., 140., 150., 140.,
        30.,  70.,  30.,  70.,  30.,  90.,  60., 130., 140., 130.,  90.,
        90., 210., 200.,  60.,  50.,  10.,  60., 150., 140., 140., 150.,
        70., 120., 140.,  60., 120., 140., 150., 140.,   5.,  10.,   5.,
         5.,   5.,   5.,   0.,   5.,  70.,   5., 110., 320., 430., 190.,
       290., 120., 250., 260., 250., 180., 130., 230., 250., 200., 260.,
       190., 300., 190., 190.,  45., 250., 360., 350., 110., 280., 140.,
       200., 200., 320., 300.])

In [107]:
niveaux_calories = np.zeros(calories.shape)
#niveaux_calories.shape

In [108]:
niveaux_calories[(calories >= 0) & (calories <= 100)] = 1.0
niveaux_calories[(calories > 100) & (calories <= 200) ] = 2.0
niveaux_calories[(calories > 200) & (calories <= 300)] = 3.0
niveaux_calories[calories > 300] = 4.0
mask_nutriscore1 = niveaux_calories == 1.0

In [109]:
print(np.unique(niveaux_calories))
print(niveaux_calories[:10])
print(mask_nutriscore1.sum())
print(mask_nutriscore1[:10])
print(filt_data.shape)
print(filt_data[:5])


[1. 2. 3. 4.]
[1. 1. 1. 2. 1. 2. 2. 2. 1. 1.]
34
[ True  True  True False  True False False False  True  True]
(92, 6)
[[ 45.   0.  11.   0.   0.  10.]
 [ 80.   0.  18.   1.   0.  10.]
 [ 60.   0.  14.   1.   0.  10.]
 [110.   0.  28.   0.   0.   5.]
 [  0.   0.   0.   0.   0.   0.]]


In [110]:
nutriscore1 = filt_data[mask_nutriscore1]

nutriscore1

array([[45.,  0., 11.,  0.,  0., 10.],
       [80.,  0., 18.,  1.,  0., 10.],
       [60.,  0., 14.,  1.,  0., 10.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [80.,  0., 19.,  0.,  0., 10.],
       [60.,  0., 15.,  0.,  0., 10.],
       [70.,  0., 17.,  0.,  0., 10.],
       [60.,  0., 15.,  0.,  0., 10.],
       [30.,  0.,  8.,  0.,  0.,  5.],
       [70.,  0., 17.,  0.,  0.,  0.],
       [30.,  0.,  8.,  0.,  0.,  5.],
       [70.,  0., 17.,  0.,  0.,  5.],
       [30.,  0.,  8.,  0.,  0.,  5.],
       [90.,  0., 24.,  0.,  0.,  0.],
       [60.,  0., 15.,  0.,  0.,  0.],
       [90.,  0., 27.,  0.,  0.,  0.],
       [90.,  0., 27.,  0.,  0.,  0.],
       [60.,  0., 13.,  0.,  1.,  0.],
       [50.,  0., 11.,  0.,  1.,  0.],
       [10.,  0.,  2.,  0.,  1.,  0.],
       [60.,  0., 15.,  0.,  0., 10.],
       [70.,  0., 17.,  0.,  0., 10.],
       [60.,  0., 15.,  0.,  0., 10.],
       [ 5.,  0.,  0.,  0.,  1., 10.],
       [10.,  0.,  0.,  0.,  1., 10.],
       [ 5.,  0.,  0.,  0

In [111]:
moyenne_calories_nutriscore1 = nutriscore1[:,0].mean()
print(f'la moyenne de calories pour les boissons ayant le nutriscore 1 est {moyenne_calories_nutriscore1}')

la moyenne de calories pour les boissons ayant le nutriscore 1 est 43.6764705882353
